# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advancedsetting2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_advancedSettings(object):

    lineEdit_numHours = 8
    lineEdit_robotSpeed = 0.8
    lineEdit_numStopSign = 0
    lineEdit_planningTime = 15
    lineEdit_trafficFactor = 0.8
    lineEdit_numShift = 3
    lineEdit_chargingFactor = 0.95
    lineEdit_dockTime = 60

    @classmethod
    def readSettings(cls,numHours, robotSpeed, numStopSign, planningTime, trafficFactor, numShift, chargingFactor, dockTime):
        '''
        This function reads the values from 'line_Edits' and stores them into class variables respectively
        '''
        cls.lineEdit_numHours = numHours
        cls.lineEdit_robotSpeed = robotSpeed
        cls.lineEdit_numStopSign = numStopSign
        cls.lineEdit_planningTime = planningTime
        cls.lineEdit_trafficFactor = trafficFactor
        cls.lineEdit_numShift = numShift
        cls.lineEdit_chargingFactor = chargingFactor
        cls.lineEdit_dockTime = dockTime

    def updateSettings(self):
        Ui_Dialog_advancedSettings.readSettings(self.lineEdit_numHours.text(), self.lineEdit_robotSpeed.text(), self.lineEdit_numStopSign.text(), self.lineEdit_planningTime.text(), self.lineEdit_trafficFactor.text(), self.lineEdit_numShift.text(), self.lineEdit_chargingFactor.text(), self.lineEdit_dockTime.text())
     
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 400)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_numHour = QtWidgets.QLabel(Dialog)
        self.label_numHour.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_numHour.setObjectName("label_numHour")
        self.gridLayout.addWidget(self.label_numHour, 1, 0, 1, 1)
        self.label_traffiFactor = QtWidgets.QLabel(Dialog)
        self.label_traffiFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_traffiFactor.setObjectName("label_traffiFactor")
        self.gridLayout.addWidget(self.label_traffiFactor, 5, 0, 1, 1)
        self.label_dockingTime = QtWidgets.QLabel(Dialog)
        self.label_dockingTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_dockingTime.setObjectName("label_dockingTime")
        self.gridLayout.addWidget(self.label_dockingTime, 6, 0, 1, 1)
        self.label_planningTime = QtWidgets.QLabel(Dialog)
        self.label_planningTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_planningTime.setObjectName("label_planningTime")
        self.gridLayout.addWidget(self.label_planningTime, 7, 0, 1, 1)
        self.lineEdit_numHours = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_numHours.setObjectName("lineEdit_numHours")
        self.gridLayout.addWidget(self.lineEdit_numHours, 1, 2, 1, 1)
        self.lineEdit_robotSpeed = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_robotSpeed.setObjectName("lineEdit_robotSpeed")
        self.gridLayout.addWidget(self.lineEdit_robotSpeed, 2, 2, 1, 1)
        self.lineEdit_numStopSign = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_numStopSign.setObjectName("lineEdit_numStopSign")
        self.gridLayout.addWidget(self.lineEdit_numStopSign, 3, 2, 1, 1)
        self.lineEdit_planningTime = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_planningTime.setObjectName("lineEdit_planningTime")
        self.gridLayout.addWidget(self.lineEdit_planningTime, 7, 2, 1, 1)
        self.label_robotSpeed = QtWidgets.QLabel(Dialog)
        self.label_robotSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_robotSpeed.setObjectName("label_robotSpeed")
        self.gridLayout.addWidget(self.label_robotSpeed, 2, 0, 1, 1)
        self.lineEdit_trafficFactor = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_trafficFactor.setObjectName("lineEdit_trafficFactor")
        self.gridLayout.addWidget(self.lineEdit_trafficFactor, 5, 2, 1, 1)
        self.label_numStopSign = QtWidgets.QLabel(Dialog)
        self.label_numStopSign.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_numStopSign.setObjectName("label_numStopSign")
        self.gridLayout.addWidget(self.label_numStopSign, 3, 0, 1, 1)
        self.lineEdit_numShift = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_numShift.setObjectName("lineEdit_numShift")
        self.gridLayout.addWidget(self.lineEdit_numShift, 0, 2, 1, 1)
        self.label_charingFactor = QtWidgets.QLabel(Dialog)
        self.label_charingFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_charingFactor.setObjectName("label_charingFactor")
        self.gridLayout.addWidget(self.label_charingFactor, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 8, 2, 1, 1)
        self.lineEdit_chargingFactor = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_chargingFactor.setObjectName("lineEdit_chargingFactor")
        self.gridLayout.addWidget(self.lineEdit_chargingFactor, 4, 2, 1, 1)
        self.lineEdit_dockTime = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dockTime.setObjectName("lineEdit_dockTime")
        self.gridLayout.addWidget(self.lineEdit_dockTime, 6, 2, 1, 1)
        self.label_numShift = QtWidgets.QLabel(Dialog)
        self.label_numShift.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_numShift.setObjectName("label_numShift")
        self.gridLayout.addWidget(self.label_numShift, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 6, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 7, 1, 1, 1)

        self.retranslateUi(Dialog)
        
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.accepted.connect(self.updateSettings)
        # self.buttonBox.clicked.connect(self.updateSettings)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        # self.buttonBox.accepted.connect(Ui_Dialog_advancedSettings.readSettings(self.lineEdit_numHours.text(), self.lineEdit_robotSpeed.text(), self.lineEdit_numStopSign.text(), self.lineEdit_planningTime.text(), self.lineEdit_trafficFactor.text(), self.lineEdit_numShift.text(), self.lineEdit_chargingFactor.text(), self.lineEdit_dockTime.text()))
        
        Ui_Dialog_advancedSettings.readSettings(self.lineEdit_numHours.text(), self.lineEdit_robotSpeed.text(), self.lineEdit_numStopSign.text(), self.lineEdit_planningTime.text(), self.lineEdit_trafficFactor.text(), self.lineEdit_numShift.text(), self.lineEdit_chargingFactor.text(), self.lineEdit_dockTime.text())
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Advanced Settings"))
        self.label_numHour.setText(_translate("Dialog", "Hours Per Shift"))
        self.label_traffiFactor.setText(_translate("Dialog", "Traffic Factor"))
        self.label_dockingTime.setText(_translate("Dialog", "Docking Time (s)"))
        self.label_planningTime.setText(_translate("Dialog", "Path Planning Time (s)"))
        self.lineEdit_numHours.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_numHours)))
        self.lineEdit_robotSpeed.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_robotSpeed)))
        self.lineEdit_numStopSign.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_numStopSign)))
        self.lineEdit_planningTime.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_planningTime)))
        self.label_robotSpeed.setText(_translate("Dialog", "Robot Speed (m/s)"))
        self.lineEdit_trafficFactor.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_robotSpeed)))
        self.label_numStopSign.setText(_translate("Dialog", "Number of Stop Sign"))
        self.lineEdit_numShift.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_numShift)))
        self.label_charingFactor.setText(_translate("Dialog", "Charging Factor"))
        self.lineEdit_chargingFactor.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_chargingFactor)))
        self.lineEdit_dockTime.setText(_translate("Dialog", str(Ui_Dialog_advancedSettings.lineEdit_dockTime)))
        self.label_numShift.setText(_translate("Dialog", "Shifts Per Day"))
        # Ui_Dialog_advancedSettings.readSettings(self.lineEdit_numHours.text(), self.lineEdit_robotSpeed.text(), self.lineEdit_numStopSign.text(), self.lineEdit_planningTime.text(), self.lineEdit_trafficFactor.text(), self.lineEdit_numShift.text(), self.lineEdit_chargingFactor.text(), self.lineEdit_dockTime.text())
#     lineEdit_numHours = 8
#     lineEdit_robotSpeed = 0
#     lineEdit_numStopSign = 0
#     lineEdit_planningTime = 15
#     lineEdit_trafficFactor = 0.8
#     lineEdit_numShift = 3
#     lineEdit_chargingFactor = 0.95
#     lineEdit_dockTime = 60
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_advancedSettings()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
